/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 *
 * From Source File: /Users/ryan/dev/symforce-zig-build/lcmtypes/symforce.lcm
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __sym_index_t_hpp__
#define __sym_index_t_hpp__

#include <ostream>
#include <vector>
#include "lcmtypes/sym/index_entry_t.hpp"

namespace sym
{

class index_t
{
    public:
        int32_t storage_dim;

        int32_t tangent_dim;

        std::vector< ::sym::index_entry_t > entries;

    public:
        index_t() = default;

        /**
         * Member constructor
         */
        inline index_t(
            const int32_t& storage_dim_arg,
            const int32_t& tangent_dim_arg,
            const std::vector< ::sym::index_entry_t >& entries_arg
        );

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline __lcm_buffer_size encode(void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline __lcm_buffer_size getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline __lcm_buffer_size decode(const void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        using type_name_array_t = const char[8];

        inline static constexpr type_name_array_t* getTypeNameArrayPtr();

        /**
         * Returns "index_t"
         */
        inline static constexpr const char* getTypeName();

        /**
         * Returns "sym"
         */
        inline static constexpr const char * getPackageName();

        // LCM support functions. Users should not call these
        inline __lcm_buffer_size _encodeNoHash(void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen) const;
        inline __lcm_buffer_size _getEncodedSizeNoHash() const;
        inline __lcm_buffer_size _decodeNoHash(const void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen);
#if !defined(SKYDIO_DISABLE_LCM_NO_INLINE)
        __attribute__((noinline))
#endif
        static uint64_t _computeHash(const __lcm_hash_ptr *p)
        {
            const __lcm_hash_ptr *fp;
            for(fp = p; fp != NULL; fp = fp->parent)
                if(fp->v == index_t::getHash)
                    return 0;
            const __lcm_hash_ptr cp = { p, index_t::getHash };

            uint64_t hash = 0xcab1ff73ad10c21eLL +
                ::sym::index_entry_t::_computeHash(&cp);

            return (hash<<1) + ((hash>>63)&1);
        }

        // Comparison operators.
        inline bool operator==(const index_t& other) const;
        inline bool operator!=(const index_t& other) const;

        // Ability to print to standard streams as well as the fmt library.
        friend std::ostream& operator<<(std::ostream& stream, const index_t& obj) {
#if defined(SKYMARSHAL_PRINTING_ENABLED)
            stream << "index_t(";
            stream << "storage_dim=" << obj.storage_dim << ", ";
            stream << "tangent_dim=" << obj.tangent_dim << ", ";
            stream << "entries=[";
            for (size_t i = 0; i < obj.entries.size(); ++i) {
                stream << obj.entries[i];
                if (i + 1 < obj.entries.size()) {
                    stream << ", ";
                }
            }
            stream << "]";
            stream << ")";
#else
            stream << "<FORMATTING DISABLED>";
#endif
            return stream;
        }
};

index_t::index_t(
    const int32_t& storage_dim_arg,
    const int32_t& tangent_dim_arg,
    const std::vector< ::sym::index_entry_t >& entries_arg
) : storage_dim(storage_dim_arg),
    tangent_dim(tangent_dim_arg),
    entries(entries_arg) {}

__lcm_buffer_size index_t::encode(void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen) const
{
    __lcm_buffer_size pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

__lcm_buffer_size index_t::decode(const void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen)
{
    __lcm_buffer_size pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

__lcm_buffer_size index_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t index_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

constexpr index_t::type_name_array_t* index_t::getTypeNameArrayPtr() {
    return &"index_t";
}

constexpr const char* index_t::getTypeName()
{
    return *index_t::getTypeNameArrayPtr();
}

constexpr const char * index_t::getPackageName()
{
    return "sym";
}

__lcm_buffer_size index_t::_encodeNoHash(void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen) const
{
    __lcm_buffer_size pos = 0, tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->storage_dim, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->tangent_dim, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t v_num_entries = this->entries.size();
    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &v_num_entries, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (__lcm_buffer_size a0 = 0; a0 < v_num_entries; a0++) {
        tlen = this->entries[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

__lcm_buffer_size index_t::_decodeNoHash(const void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen)
{
    __lcm_buffer_size pos = 0, tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->storage_dim, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->tangent_dim, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t v_num_entries;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &v_num_entries, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->entries.resize(v_num_entries);
    for (__lcm_buffer_size a0 = 0; a0 < v_num_entries; a0++) {
        tlen = this->entries[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

__lcm_buffer_size index_t::_getEncodedSizeNoHash() const
{
    __lcm_buffer_size enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (__lcm_buffer_size a0 = 0; a0 < this->entries.size(); a0++) {
        enc_size += this->entries[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

bool index_t::operator==(const index_t& other) const {
  return (
          (storage_dim==other.storage_dim) && 
          (tangent_dim==other.tangent_dim) && 
          (entries==other.entries));
}

bool index_t::operator!=(const index_t& other) const {
  return !(*this==other);
}

}

#endif